/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Validate.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Validate.Model
{
    /// <summary>
    /// Result of performing an Admin Path operation
    /// </summary>
    [DataContract]
    public partial class IsAdminPathResponse :  IEquatable<IsAdminPathResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IsAdminPathResponse" /> class.
        /// </summary>
        /// <param name="isAdminPathNode">True if the input IP address is an Admin Path, and false otherwise.</param>
        /// <param name="successful">True if the operation was successful, false otherwise.</param>
        public IsAdminPathResponse(bool? isAdminPathNode = default(bool?), bool? successful = default(bool?))
        {
            this.IsAdminPathNode = isAdminPathNode;
            this.Successful = successful;
        }
        
        /// <summary>
        /// True if the input IP address is an Admin Path, and false otherwise
        /// </summary>
        /// <value>True if the input IP address is an Admin Path, and false otherwise</value>
        [DataMember(Name="IsAdminPathNode", EmitDefaultValue=false)]
        public bool? IsAdminPathNode { get; set; }

        /// <summary>
        /// True if the operation was successful, false otherwise
        /// </summary>
        /// <value>True if the operation was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IsAdminPathResponse {\n");
            sb.Append("  IsAdminPathNode: ").Append(IsAdminPathNode).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IsAdminPathResponse);
        }

        /// <summary>
        /// Returns true if IsAdminPathResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of IsAdminPathResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IsAdminPathResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsAdminPathNode == input.IsAdminPathNode ||
                    (this.IsAdminPathNode != null &&
                    this.IsAdminPathNode.Equals(input.IsAdminPathNode))
                ) && 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsAdminPathNode != null)
                    hashCode = hashCode * 59 + this.IsAdminPathNode.GetHashCode();
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
