/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Validate.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Validate.Model
{
    /// <summary>
    /// Result of performing a Tor node check on an IP address
    /// </summary>
    [DataContract]
    public partial class TorNodeResponse :  IEquatable<TorNodeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TorNodeResponse" /> class.
        /// </summary>
        /// <param name="isTorNode">True if the input IP address is a Tor exit node, false otherwise.</param>
        public TorNodeResponse(bool? isTorNode = default(bool?))
        {
            this.IsTorNode = isTorNode;
        }
        
        /// <summary>
        /// True if the input IP address is a Tor exit node, false otherwise
        /// </summary>
        /// <value>True if the input IP address is a Tor exit node, false otherwise</value>
        [DataMember(Name="IsTorNode", EmitDefaultValue=false)]
        public bool? IsTorNode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TorNodeResponse {\n");
            sb.Append("  IsTorNode: ").Append(IsTorNode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TorNodeResponse);
        }

        /// <summary>
        /// Returns true if TorNodeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TorNodeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TorNodeResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsTorNode == input.IsTorNode ||
                    (this.IsTorNode != null &&
                    this.IsTorNode.Equals(input.IsTorNode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsTorNode != null)
                    hashCode = hashCode * 59 + this.IsTorNode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
