/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Validate.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Validate.Model
{
    /// <summary>
    /// Result of checking a URL for HTML-embedded SSRF threats
    /// </summary>
    [DataContract]
    public partial class UrlHtmlSsrfResponseFull :  IEquatable<UrlHtmlSsrfResponseFull>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UrlHtmlSsrfResponseFull" /> class.
        /// </summary>
        /// <param name="cleanURL">True if the URL is clean, false if it is at risk of containing an SSRF threat or attack.</param>
        /// <param name="httpResponseCode">HTTP response code from the URL.</param>
        public UrlHtmlSsrfResponseFull(bool? cleanURL = default(bool?), int? httpResponseCode = default(int?))
        {
            this.CleanURL = cleanURL;
            this.HttpResponseCode = httpResponseCode;
        }
        
        /// <summary>
        /// True if the URL is clean, false if it is at risk of containing an SSRF threat or attack
        /// </summary>
        /// <value>True if the URL is clean, false if it is at risk of containing an SSRF threat or attack</value>
        [DataMember(Name="CleanURL", EmitDefaultValue=false)]
        public bool? CleanURL { get; set; }

        /// <summary>
        /// HTTP response code from the URL
        /// </summary>
        /// <value>HTTP response code from the URL</value>
        [DataMember(Name="HttpResponseCode", EmitDefaultValue=false)]
        public int? HttpResponseCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UrlHtmlSsrfResponseFull {\n");
            sb.Append("  CleanURL: ").Append(CleanURL).Append("\n");
            sb.Append("  HttpResponseCode: ").Append(HttpResponseCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UrlHtmlSsrfResponseFull);
        }

        /// <summary>
        /// Returns true if UrlHtmlSsrfResponseFull instances are equal
        /// </summary>
        /// <param name="input">Instance of UrlHtmlSsrfResponseFull to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UrlHtmlSsrfResponseFull input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanURL == input.CleanURL ||
                    (this.CleanURL != null &&
                    this.CleanURL.Equals(input.CleanURL))
                ) && 
                (
                    this.HttpResponseCode == input.HttpResponseCode ||
                    (this.HttpResponseCode != null &&
                    this.HttpResponseCode.Equals(input.HttpResponseCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanURL != null)
                    hashCode = hashCode * 59 + this.CleanURL.GetHashCode();
                if (this.HttpResponseCode != null)
                    hashCode = hashCode * 59 + this.HttpResponseCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
