/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Validate.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Validate.Model
{
    /// <summary>
    /// Batch operation to perform SSRF threat checks on multiple URLs
    /// </summary>
    [DataContract]
    public partial class UrlSsrfRequestBatch :  IEquatable<UrlSsrfRequestBatch>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UrlSsrfRequestBatch" /> class.
        /// </summary>
        /// <param name="inputItems">Input URLs to check for SSRF threats.</param>
        public UrlSsrfRequestBatch(List<UrlSsrfRequestFull> inputItems = default(List<UrlSsrfRequestFull>))
        {
            this.InputItems = inputItems;
        }
        
        /// <summary>
        /// Input URLs to check for SSRF threats
        /// </summary>
        /// <value>Input URLs to check for SSRF threats</value>
        [DataMember(Name="InputItems", EmitDefaultValue=false)]
        public List<UrlSsrfRequestFull> InputItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UrlSsrfRequestBatch {\n");
            sb.Append("  InputItems: ").Append(InputItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UrlSsrfRequestBatch);
        }

        /// <summary>
        /// Returns true if UrlSsrfRequestBatch instances are equal
        /// </summary>
        /// <param name="input">Instance of UrlSsrfRequestBatch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UrlSsrfRequestBatch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputItems == input.InputItems ||
                    this.InputItems != null &&
                    this.InputItems.SequenceEqual(input.InputItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputItems != null)
                    hashCode = hashCode * 59 + this.InputItems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
