/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Validate.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Validate.Model
{
    /// <summary>
    /// Result of performing an identifier validation operation
    /// </summary>
    [DataContract]
    public partial class ValidateIdentifierResponse :  IEquatable<ValidateIdentifierResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateIdentifierResponse" /> class.
        /// </summary>
        /// <param name="validIdentifier">True if the input identifier is valid, false otherwise.</param>
        /// <param name="error">Resulting error from the identifier validation; possible errors are: \&quot;InputIsEmpty\&quot;, \&quot;ContainsWhitespace\&quot;, \&quot;ContainsNumbers\&quot;, \&quot;ContainsHyphen\&quot;, \&quot;ContainsUnderscore\&quot;, \&quot;ContainsPeriod\&quot;, \&quot;TooShort\&quot;, \&quot;TooLong\&quot;, \&quot;ContainsSpecialCharacters\&quot;.</param>
        public ValidateIdentifierResponse(bool? validIdentifier = default(bool?), string error = default(string))
        {
            this.ValidIdentifier = validIdentifier;
            this.Error = error;
        }
        
        /// <summary>
        /// True if the input identifier is valid, false otherwise
        /// </summary>
        /// <value>True if the input identifier is valid, false otherwise</value>
        [DataMember(Name="ValidIdentifier", EmitDefaultValue=false)]
        public bool? ValidIdentifier { get; set; }

        /// <summary>
        /// Resulting error from the identifier validation; possible errors are: \&quot;InputIsEmpty\&quot;, \&quot;ContainsWhitespace\&quot;, \&quot;ContainsNumbers\&quot;, \&quot;ContainsHyphen\&quot;, \&quot;ContainsUnderscore\&quot;, \&quot;ContainsPeriod\&quot;, \&quot;TooShort\&quot;, \&quot;TooLong\&quot;, \&quot;ContainsSpecialCharacters\&quot;
        /// </summary>
        /// <value>Resulting error from the identifier validation; possible errors are: \&quot;InputIsEmpty\&quot;, \&quot;ContainsWhitespace\&quot;, \&quot;ContainsNumbers\&quot;, \&quot;ContainsHyphen\&quot;, \&quot;ContainsUnderscore\&quot;, \&quot;ContainsPeriod\&quot;, \&quot;TooShort\&quot;, \&quot;TooLong\&quot;, \&quot;ContainsSpecialCharacters\&quot;</value>
        [DataMember(Name="Error", EmitDefaultValue=false)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValidateIdentifierResponse {\n");
            sb.Append("  ValidIdentifier: ").Append(ValidIdentifier).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValidateIdentifierResponse);
        }

        /// <summary>
        /// Returns true if ValidateIdentifierResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ValidateIdentifierResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidateIdentifierResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ValidIdentifier == input.ValidIdentifier ||
                    (this.ValidIdentifier != null &&
                    this.ValidIdentifier.Equals(input.ValidIdentifier))
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ValidIdentifier != null)
                    hashCode = hashCode * 59 + this.ValidIdentifier.GetHashCode();
                if (this.Error != null)
                    hashCode = hashCode * 59 + this.Error.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
