/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing FullEmailValidationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FullEmailValidationResponseTests
    {
        // TODO uncomment below to declare an instance variable for FullEmailValidationResponse
        //private FullEmailValidationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FullEmailValidationResponse
            //instance = new FullEmailValidationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FullEmailValidationResponse
        /// </summary>
        [Test]
        public void FullEmailValidationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FullEmailValidationResponse
            //Assert.IsInstanceOfType<FullEmailValidationResponse> (instance, "variable 'instance' is a FullEmailValidationResponse");
        }


        /// <summary>
        /// Test the property 'ValidAddress'
        /// </summary>
        [Test]
        public void ValidAddressTest()
        {
            // TODO unit test for the property 'ValidAddress'
        }
        /// <summary>
        /// Test the property 'MailServerUsedForValidation'
        /// </summary>
        [Test]
        public void MailServerUsedForValidationTest()
        {
            // TODO unit test for the property 'MailServerUsedForValidation'
        }
        /// <summary>
        /// Test the property 'ValidSyntax'
        /// </summary>
        [Test]
        public void ValidSyntaxTest()
        {
            // TODO unit test for the property 'ValidSyntax'
        }
        /// <summary>
        /// Test the property 'ValidDomain'
        /// </summary>
        [Test]
        public void ValidDomainTest()
        {
            // TODO unit test for the property 'ValidDomain'
        }
        /// <summary>
        /// Test the property 'ValidSMTP'
        /// </summary>
        [Test]
        public void ValidSMTPTest()
        {
            // TODO unit test for the property 'ValidSMTP'
        }
        /// <summary>
        /// Test the property 'IsCatchallDomain'
        /// </summary>
        [Test]
        public void IsCatchallDomainTest()
        {
            // TODO unit test for the property 'IsCatchallDomain'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

    }

}
