/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing FullNameValidationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FullNameValidationResponseTests
    {
        // TODO uncomment below to declare an instance variable for FullNameValidationResponse
        //private FullNameValidationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FullNameValidationResponse
            //instance = new FullNameValidationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FullNameValidationResponse
        /// </summary>
        [Test]
        public void FullNameValidationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FullNameValidationResponse
            //Assert.IsInstanceOfType<FullNameValidationResponse> (instance, "variable 'instance' is a FullNameValidationResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ValidationResultFirstName'
        /// </summary>
        [Test]
        public void ValidationResultFirstNameTest()
        {
            // TODO unit test for the property 'ValidationResultFirstName'
        }
        /// <summary>
        /// Test the property 'ValidationResultLastName'
        /// </summary>
        [Test]
        public void ValidationResultLastNameTest()
        {
            // TODO unit test for the property 'ValidationResultLastName'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Test]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'NickName'
        /// </summary>
        [Test]
        public void NickNameTest()
        {
            // TODO unit test for the property 'NickName'
        }
        /// <summary>
        /// Test the property 'Suffix'
        /// </summary>
        [Test]
        public void SuffixTest()
        {
            // TODO unit test for the property 'Suffix'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

    }

}
