/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing LeadEnrichmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeadEnrichmentRequestTests
    {
        // TODO uncomment below to declare an instance variable for LeadEnrichmentRequest
        //private LeadEnrichmentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LeadEnrichmentRequest
            //instance = new LeadEnrichmentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeadEnrichmentRequest
        /// </summary>
        [Test]
        public void LeadEnrichmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeadEnrichmentRequest
            //Assert.IsInstanceOfType<LeadEnrichmentRequest> (instance, "variable 'instance' is a LeadEnrichmentRequest");
        }


        /// <summary>
        /// Test the property 'ContactBusinessEmail'
        /// </summary>
        [Test]
        public void ContactBusinessEmailTest()
        {
            // TODO unit test for the property 'ContactBusinessEmail'
        }
        /// <summary>
        /// Test the property 'ContactFirstName'
        /// </summary>
        [Test]
        public void ContactFirstNameTest()
        {
            // TODO unit test for the property 'ContactFirstName'
        }
        /// <summary>
        /// Test the property 'ContactLastName'
        /// </summary>
        [Test]
        public void ContactLastNameTest()
        {
            // TODO unit test for the property 'ContactLastName'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyDomainName'
        /// </summary>
        [Test]
        public void CompanyDomainNameTest()
        {
            // TODO unit test for the property 'CompanyDomainName'
        }
        /// <summary>
        /// Test the property 'CompanyHouseNumber'
        /// </summary>
        [Test]
        public void CompanyHouseNumberTest()
        {
            // TODO unit test for the property 'CompanyHouseNumber'
        }
        /// <summary>
        /// Test the property 'CompanyStreet'
        /// </summary>
        [Test]
        public void CompanyStreetTest()
        {
            // TODO unit test for the property 'CompanyStreet'
        }
        /// <summary>
        /// Test the property 'CompanyCity'
        /// </summary>
        [Test]
        public void CompanyCityTest()
        {
            // TODO unit test for the property 'CompanyCity'
        }
        /// <summary>
        /// Test the property 'CompanyStateOrProvince'
        /// </summary>
        [Test]
        public void CompanyStateOrProvinceTest()
        {
            // TODO unit test for the property 'CompanyStateOrProvince'
        }
        /// <summary>
        /// Test the property 'CompanyPostalCode'
        /// </summary>
        [Test]
        public void CompanyPostalCodeTest()
        {
            // TODO unit test for the property 'CompanyPostalCode'
        }
        /// <summary>
        /// Test the property 'CompanyCountry'
        /// </summary>
        [Test]
        public void CompanyCountryTest()
        {
            // TODO unit test for the property 'CompanyCountry'
        }
        /// <summary>
        /// Test the property 'CompanyCountryCode'
        /// </summary>
        [Test]
        public void CompanyCountryCodeTest()
        {
            // TODO unit test for the property 'CompanyCountryCode'
        }
        /// <summary>
        /// Test the property 'CompanyTelephone'
        /// </summary>
        [Test]
        public void CompanyTelephoneTest()
        {
            // TODO unit test for the property 'CompanyTelephone'
        }
        /// <summary>
        /// Test the property 'CompanyVATNumber'
        /// </summary>
        [Test]
        public void CompanyVATNumberTest()
        {
            // TODO unit test for the property 'CompanyVATNumber'
        }

    }

}
