/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing NormalizeAddressResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NormalizeAddressResponseTests
    {
        // TODO uncomment below to declare an instance variable for NormalizeAddressResponse
        //private NormalizeAddressResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NormalizeAddressResponse
            //instance = new NormalizeAddressResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NormalizeAddressResponse
        /// </summary>
        [Test]
        public void NormalizeAddressResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NormalizeAddressResponse
            //Assert.IsInstanceOfType<NormalizeAddressResponse> (instance, "variable 'instance' is a NormalizeAddressResponse");
        }


        /// <summary>
        /// Test the property 'ValidAddress'
        /// </summary>
        [Test]
        public void ValidAddressTest()
        {
            // TODO unit test for the property 'ValidAddress'
        }
        /// <summary>
        /// Test the property 'Building'
        /// </summary>
        [Test]
        public void BuildingTest()
        {
            // TODO unit test for the property 'Building'
        }
        /// <summary>
        /// Test the property 'StreetNumber'
        /// </summary>
        [Test]
        public void StreetNumberTest()
        {
            // TODO unit test for the property 'StreetNumber'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'StateOrProvince'
        /// </summary>
        [Test]
        public void StateOrProvinceTest()
        {
            // TODO unit test for the property 'StateOrProvince'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'CountryFullName'
        /// </summary>
        [Test]
        public void CountryFullNameTest()
        {
            // TODO unit test for the property 'CountryFullName'
        }
        /// <summary>
        /// Test the property 'ISOTwoLetterCode'
        /// </summary>
        [Test]
        public void ISOTwoLetterCodeTest()
        {
            // TODO unit test for the property 'ISOTwoLetterCode'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
