/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing PublicHolidayOccurrence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicHolidayOccurrenceTests
    {
        // TODO uncomment below to declare an instance variable for PublicHolidayOccurrence
        //private PublicHolidayOccurrence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicHolidayOccurrence
            //instance = new PublicHolidayOccurrence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicHolidayOccurrence
        /// </summary>
        [Test]
        public void PublicHolidayOccurrenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicHolidayOccurrence
            //Assert.IsInstanceOfType<PublicHolidayOccurrence> (instance, "variable 'instance' is a PublicHolidayOccurrence");
        }


        /// <summary>
        /// Test the property 'EnglishName'
        /// </summary>
        [Test]
        public void EnglishNameTest()
        {
            // TODO unit test for the property 'EnglishName'
        }
        /// <summary>
        /// Test the property 'LocalName'
        /// </summary>
        [Test]
        public void LocalNameTest()
        {
            // TODO unit test for the property 'LocalName'
        }
        /// <summary>
        /// Test the property 'OccurrenceDate'
        /// </summary>
        [Test]
        public void OccurrenceDateTest()
        {
            // TODO unit test for the property 'OccurrenceDate'
        }
        /// <summary>
        /// Test the property 'HolidayType'
        /// </summary>
        [Test]
        public void HolidayTypeTest()
        {
            // TODO unit test for the property 'HolidayType'
        }
        /// <summary>
        /// Test the property 'Nationwaide'
        /// </summary>
        [Test]
        public void NationwaideTest()
        {
            // TODO unit test for the property 'Nationwaide'
        }

    }

}
