/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing ReverseGeocodeAddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReverseGeocodeAddressRequestTests
    {
        // TODO uncomment below to declare an instance variable for ReverseGeocodeAddressRequest
        //private ReverseGeocodeAddressRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReverseGeocodeAddressRequest
            //instance = new ReverseGeocodeAddressRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReverseGeocodeAddressRequest
        /// </summary>
        [Test]
        public void ReverseGeocodeAddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReverseGeocodeAddressRequest
            //Assert.IsInstanceOfType<ReverseGeocodeAddressRequest> (instance, "variable 'instance' is a ReverseGeocodeAddressRequest");
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
