/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing UserAgentValidateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserAgentValidateResponseTests
    {
        // TODO uncomment below to declare an instance variable for UserAgentValidateResponse
        //private UserAgentValidateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserAgentValidateResponse
            //instance = new UserAgentValidateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAgentValidateResponse
        /// </summary>
        [Test]
        public void UserAgentValidateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAgentValidateResponse
            //Assert.IsInstanceOfType<UserAgentValidateResponse> (instance, "variable 'instance' is a UserAgentValidateResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'IsBot'
        /// </summary>
        [Test]
        public void IsBotTest()
        {
            // TODO unit test for the property 'IsBot'
        }
        /// <summary>
        /// Test the property 'BotName'
        /// </summary>
        [Test]
        public void BotNameTest()
        {
            // TODO unit test for the property 'BotName'
        }
        /// <summary>
        /// Test the property 'BotURL'
        /// </summary>
        [Test]
        public void BotURLTest()
        {
            // TODO unit test for the property 'BotURL'
        }
        /// <summary>
        /// Test the property 'OperatingSystem'
        /// </summary>
        [Test]
        public void OperatingSystemTest()
        {
            // TODO unit test for the property 'OperatingSystem'
        }
        /// <summary>
        /// Test the property 'OperatingSystemCPUPlatform'
        /// </summary>
        [Test]
        public void OperatingSystemCPUPlatformTest()
        {
            // TODO unit test for the property 'OperatingSystemCPUPlatform'
        }
        /// <summary>
        /// Test the property 'OperatingSystemVersion'
        /// </summary>
        [Test]
        public void OperatingSystemVersionTest()
        {
            // TODO unit test for the property 'OperatingSystemVersion'
        }
        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Test]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
        /// <summary>
        /// Test the property 'DeviceBrandName'
        /// </summary>
        [Test]
        public void DeviceBrandNameTest()
        {
            // TODO unit test for the property 'DeviceBrandName'
        }
        /// <summary>
        /// Test the property 'DeviceModel'
        /// </summary>
        [Test]
        public void DeviceModelTest()
        {
            // TODO unit test for the property 'DeviceModel'
        }
        /// <summary>
        /// Test the property 'BrowserName'
        /// </summary>
        [Test]
        public void BrowserNameTest()
        {
            // TODO unit test for the property 'BrowserName'
        }
        /// <summary>
        /// Test the property 'BrowserVersion'
        /// </summary>
        [Test]
        public void BrowserVersionTest()
        {
            // TODO unit test for the property 'BrowserVersion'
        }
        /// <summary>
        /// Test the property 'BrowserEngineName'
        /// </summary>
        [Test]
        public void BrowserEngineNameTest()
        {
            // TODO unit test for the property 'BrowserEngineName'
        }
        /// <summary>
        /// Test the property 'BrowserEngineVersion'
        /// </summary>
        [Test]
        public void BrowserEngineVersionTest()
        {
            // TODO unit test for the property 'BrowserEngineVersion'
        }

    }

}
