/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing ValidateIdentifierRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValidateIdentifierRequestTests
    {
        // TODO uncomment below to declare an instance variable for ValidateIdentifierRequest
        //private ValidateIdentifierRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidateIdentifierRequest
            //instance = new ValidateIdentifierRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateIdentifierRequest
        /// </summary>
        [Test]
        public void ValidateIdentifierRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValidateIdentifierRequest
            //Assert.IsInstanceOfType<ValidateIdentifierRequest> (instance, "variable 'instance' is a ValidateIdentifierRequest");
        }


        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'AllowWhitespace'
        /// </summary>
        [Test]
        public void AllowWhitespaceTest()
        {
            // TODO unit test for the property 'AllowWhitespace'
        }
        /// <summary>
        /// Test the property 'AllowHyphens'
        /// </summary>
        [Test]
        public void AllowHyphensTest()
        {
            // TODO unit test for the property 'AllowHyphens'
        }
        /// <summary>
        /// Test the property 'AllowUnderscore'
        /// </summary>
        [Test]
        public void AllowUnderscoreTest()
        {
            // TODO unit test for the property 'AllowUnderscore'
        }
        /// <summary>
        /// Test the property 'AllowNumbers'
        /// </summary>
        [Test]
        public void AllowNumbersTest()
        {
            // TODO unit test for the property 'AllowNumbers'
        }
        /// <summary>
        /// Test the property 'AllowPeriods'
        /// </summary>
        [Test]
        public void AllowPeriodsTest()
        {
            // TODO unit test for the property 'AllowPeriods'
        }
        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Test]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }
        /// <summary>
        /// Test the property 'MinLength'
        /// </summary>
        [Test]
        public void MinLengthTest()
        {
            // TODO unit test for the property 'MinLength'
        }

    }

}
