/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing VatLookupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VatLookupResponseTests
    {
        // TODO uncomment below to declare an instance variable for VatLookupResponse
        //private VatLookupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VatLookupResponse
            //instance = new VatLookupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VatLookupResponse
        /// </summary>
        [Test]
        public void VatLookupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VatLookupResponse
            //Assert.IsInstanceOfType<VatLookupResponse> (instance, "variable 'instance' is a VatLookupResponse");
        }


        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Test]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'IsValid'
        /// </summary>
        [Test]
        public void IsValidTest()
        {
            // TODO unit test for the property 'IsValid'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'BusinessAddress'
        /// </summary>
        [Test]
        public void BusinessAddressTest()
        {
            // TODO unit test for the property 'BusinessAddress'
        }

    }

}
