/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing XssProtectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class XssProtectionResultTests
    {
        // TODO uncomment below to declare an instance variable for XssProtectionResult
        //private XssProtectionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XssProtectionResult
            //instance = new XssProtectionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XssProtectionResult
        /// </summary>
        [Test]
        public void XssProtectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" XssProtectionResult
            //Assert.IsInstanceOfType<XssProtectionResult> (instance, "variable 'instance' is a XssProtectionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ContainedXss'
        /// </summary>
        [Test]
        public void ContainedXssTest()
        {
            // TODO unit test for the property 'ContainedXss'
        }
        /// <summary>
        /// Test the property 'OriginalInput'
        /// </summary>
        [Test]
        public void OriginalInputTest()
        {
            // TODO unit test for the property 'OriginalInput'
        }
        /// <summary>
        /// Test the property 'NormalizedResult'
        /// </summary>
        [Test]
        public void NormalizedResultTest()
        {
            // TODO unit test for the property 'NormalizedResult'
        }

    }

}
