/* 
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Validate.Api;
using Cloudmersive.APIClient.NET.Validate.Model;
using Cloudmersive.APIClient.NET.Validate.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Validate.Test
{
    /// <summary>
    ///  Class for testing XxeDetectionRequestItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class XxeDetectionRequestItemTests
    {
        // TODO uncomment below to declare an instance variable for XxeDetectionRequestItem
        //private XxeDetectionRequestItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XxeDetectionRequestItem
            //instance = new XxeDetectionRequestItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XxeDetectionRequestItem
        /// </summary>
        [Test]
        public void XxeDetectionRequestItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" XxeDetectionRequestItem
            //Assert.IsInstanceOfType<XxeDetectionRequestItem> (instance, "variable 'instance' is a XxeDetectionRequestItem");
        }


        /// <summary>
        /// Test the property 'InputText'
        /// </summary>
        [Test]
        public void InputTextTest()
        {
            // TODO unit test for the property 'InputText'
        }
        /// <summary>
        /// Test the property 'AllowInternetUrls'
        /// </summary>
        [Test]
        public void AllowInternetUrlsTest()
        {
            // TODO unit test for the property 'AllowInternetUrls'
        }
        /// <summary>
        /// Test the property 'KnownSafeUrls'
        /// </summary>
        [Test]
        public void KnownSafeUrlsTest()
        {
            // TODO unit test for the property 'KnownSafeUrls'
        }
        /// <summary>
        /// Test the property 'KnownUnsafeUrls'
        /// </summary>
        [Test]
        public void KnownUnsafeUrlsTest()
        {
            // TODO unit test for the property 'KnownUnsafeUrls'
        }

    }

}
